services:
  - type: web
    name: fincollect-backend
    env: node
    branch: main
    repo: https://github.com/ARDRASATHYAN/fincollect_backend
    buildCommand: "npm install"
    startCommand: "npm start"
    plan: free
    envVars:
      - key: PORT
        value: "5000"

      - key: DB_HOST
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_PORT
        sync: false

      - key: MAIL_HOST
        sync: false
      - key: MAIL_PORT
        sync: false
      - key: MAIL_USER
        sync: false
      - key: MAIL_PASS
        sync: false

      - key: FRONTEND_URL
        sync: false
